---
version: '3.9'

services:
  runner:
    image: https://github.com/mukaschultze/docker-github-runner-linux.git
    build:
      context: .
      args:
        RUNNER_VERSION: '2.292.0'
    environment:
      GH_TOKEN: ${GH_TOKEN}
      GH_OWNER: ${GH_OWNER}
      GH_REPOSITORY: ${GH_REPOSITORY}